services:
  postgres-db:
    image: postgres:15.3
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
